"""Process the patch files generated by extractPatches.py and prepare
them for analysis by Kmeans and diffusion-maps"""
from lib.utils import *
from glob import glob
import pickle as pk
from os import system
import numpy as np
from os.path import isdir
from minio import Minio

import pickle as pk
import numpy as np
from glob import glob

from os import mkdir

from lib.permute import permutator

class Sorter:

    def __init__(self):
        self.Permutators={}

    def sort_file(pkl_file):
        #print(pkl_file)
        V=pk.load(open(pkl_file,'rb'))

        for e in V:
            size = e['padded_size']
            tile=e['padded_patch']
            if tile is None:
                continue
            asbytes = bytearray(tile.tobytes())
            #print('size:',size,len(asbytes))

            if size in Permutators:
                Permutators[size].push(asbytes)
            else:
                Permutators[size] = permutator(asbytes)
                Permutators[size].push(asbytes)
    def close(stem='permuted-'):
        for size in Permutators.keys():
            Permutator=Permutators[size]
            Permutator.combine('%s-%d'%(stem,size))

if __name__=='__main__':
    
